version: '3.6'

services:

  my-app-tp_5:
    container_name: my_app_tp_5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
